### ISSUE TITLE
N-API node test failing in CI

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1719]
All the node tests pass now in CI except the N-API test.  The test action (https://github.com/RecordReplay/devtools/runs/1845112414?check_suite_focus=true) shows this error:

```
/Users/runner/work/devtools/devtools/node_modules/sharp/lib/libvips.js:62
      throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
      ^

Error: 'linux-x64' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'darwin-x64' platform.
    at Object.hasVendoredLibvips (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/libvips.js:62:13)
    at Object.<anonymous> (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/constructor.js:7:22)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
```

Looking at the distribution we have prebuilt cross-platform binaries for utf8-validate and bufferutil, but for sharp the original C sources are present and only the linux binary is built.  The action builds the distribution on linux, and I guess sharp doesn't provide prebuilt binaries so we end up only being able to target linux and can't run the test on macOS.

Rather than rejigger the test or the actions to support this test, we should just avoid running it in CI.  Soon we'll be running our tests on linux as well and will have coverage for this test.

**Comment by bhackett1024** [comment]
Actually, this doesn't feel right, we shouldn't be using workarounds like this and we should have coverage for the N-API test on macOS and not just linux.  If we build the webpack on macOS instead of linux I think this will be fixed, let's see...
