### ISSUE TITLE
node_napi test is failing consistently

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2557]
The node_napi test is failing consistently at 

>  Starting warpToMessage iVBORw0KGgoAAAANSUhEUgAAAAQAAAAFCAYAAA

https://replay.io/view?id=cb98e11d-dc99-40bb-9036-77060cc5ceff&point=28557632723508785027577054037541318&time=21686.501717106676&hasFrames=true

https://replay.io/view?id=82b5ba51-d583-4545-a5b0-612d0da95f68&point=378388633567598957111210631711688302&time=181940&hasFrames=false

https://replay.io/view?id=bccfc0e8-3c69-47df-8aaa-f083a81b7a43

**Comment by bhackett1024** [comment]
This is a regression from https://github.com/RecordReplay/devtools/pull/2537
The first run where this started failing: https://github.com/RecordReplay/devtools/actions/runs/818380373

The logs in this first run don't actually include node_napi due to earlier failures, but here is the log from a more recent run:

```
2021-05-13T23:59:42.0225450Z [268.01] Starting test node_napi.js target node
2021-05-13T23:59:42.8093490Z Attach Pid 2387 BuildId macOS-node-20210328-524438650 Version linker-macOS-4974-cc71dfd4
2021-05-13T23:59:42.8123970Z [2387/1 0.004] AttachBinary /Users/runner/work/devtools/devtools/replay-node/macOS-replay-node
2021-05-13T23:59:42.8152890Z Mapped /Users/runner/work/devtools/devtools/replay-node/macOS-replay-node: 0x97ef000 [4372025344 bytes]
2021-05-13T23:59:42.8302860Z [2387/1 0.016] SendMessage 1 Internal.createRecording
2021-05-13T23:59:43.0234570Z Mapped /Users/runner/work/devtools/devtools/node_modules/utf-8-validate/prebuilds/darwin-x64/node.napi.node: 0x113128000 [8948 bytes]
2021-05-13T23:59:43.0443660Z true
2021-05-13T23:59:43.1622450Z /Users/runner/work/devtools/devtools/node_modules/sharp/lib/libvips.js:62
2021-05-13T23:59:43.1725360Z       throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
2021-05-13T23:59:43.1824430Z       ^
2021-05-13T23:59:43.1925570Z 
2021-05-13T23:59:43.2028850Z Error: 'linux-x64' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'darwin-x64' platform.
2021-05-13T23:59:43.2128890Z     at Object.hasVendoredLibvips (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/libvips.js:62:13)
2021-05-13T23:59:43.2231180Z     at Object.<anonymous> (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/constructor.js:7:22)
2021-05-13T23:59:43.2290950Z     at Module._compile (node:internal/modules/cjs/loader:1102:14)
2021-05-13T23:59:43.2379570Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
2021-05-13T23:59:43.2469040Z     at Module.load (node:internal/modules/cjs/loader:967:32)
2021-05-13T23:59:43.2480930Z     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
2021-05-13T23:59:43.2499510Z     at Module.require (node:internal/modules/cjs/loader:991:19)
2021-05-13T23:59:43.2525080Z     at require (node:internal/modules/cjs/helpers:92:18)
2021-05-13T23:59:43.2539030Z     at Object.<anonymous> (/Users/runner/work/devtools/devtools/node_modules/sharp/lib/index.js:3:15)
2021-05-13T23:59:43.2561260Z     at Module._compile (node:internal/modules/cjs/loader:1102:14)
```

The problem is that the PR changed the platform where we install dependencies for the test runner from macOS to ubuntu.  This test needs macOS specific binaries for the sharp module, so the installation needs to happen on macOS (or we need another way of dealing with this).

**Comment by jazzdan** [comment]
Ahhh that's why we ran the tests on macOS
