### ISSUE TITLE
[Debugger] inlinePreview refs is undefined

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#588]
https://sentry.io/organizations/replay/issues/1877770381/?project=5399075&referrer=alert_email

```
TypeError: can't access property "length", a.refs is undefined
  at getBindingValues(./src/devtools/client/debugger/src/actions/pause/inlinePreview.js:150:16)
  at map(./src/devtools/client/debugger/src/actions/pause/inlinePreview.js:87:38)
  at action(./src/devtools/client/debugger/src/actions/pause/inlinePreview.js:75:47)
  at apply(./src/devtools/client/debugger/src/actions/utils/middleware/thunk.js:21:11)
  at dispatch(./src/devtools/client/shared/vendor/redux.js:681:28)
  at apply(./src/devtools/client/debugger/src/actions/pause/fetchScopes.js:27:7)

```
```js
// counted as different )
  const identifiers = new Set();
  // We start from end as we want to show values besides variable
  // located nearest to the breakpoint
  for (let i = binding.refs.length - 1; i >= 0; i--) {
    const ref = binding.refs[i];
    // Subtracting 1 from line as codemirror lines are 0 indexed
    const line = ref.start.line - 1;
    const column = ref.start.column;
    // We don't want to render inline preview below the paused line
```

**Comment by hbenl** [comment]
I tried reproducing this by creating an empty scope, but in that case `binding.refs` was an empty array, not `undefined`.
This seems to have happened only once in the last 13 days, so it isn't affecting many people and I guess it will be hard to reproduce.
I propose extending the existing guard in the `getBindingValues()` function (see #664). This won't introduce a new bug, in the worst case there is a deeper issue and this fix will only change the symptoms. But we're probably not making the issue worse and may well be fixing it.

**Comment by jasonLaster** [comment]
Sounds good.
